plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: '3.3'
  NewCops: enable
  Exclude:
    - Rakefile
    - 'vendor/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

RSpec/MultipleExpectations:
  Max: 5

Metrics/AbcSize:
  Enabled: false
